/**
 * 顧客テーブル作成
 * Author:  17JZ0135
 * Created: 2018/12/20
 */
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
    TELNO          VARCHAR(11),
    NAME        VARCHAR(20),
    ADDRESS  VARCHAR(40),
    ORDERCOUNT INTEGER DEFAULT 0,
    SERVICECOUNT INTEGER DEFAULT 0,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (TELNO)
    
);
