DELETE FROM ITEM;

INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('ベトナム風ハムバンミー', 750);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('ビーフバンミー', 850);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('チキンバンミー', 750);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('照り焼きポークバンミー', 800);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('エビとアボカドバンミー', 800);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('生春巻き', 500);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('コーラMサイズ', 200);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('コーラLサイズ', 300);


