
DROP TABLE ORDERDETAIL;    


     


CREATE TABLE ORDERDETAIL (
 ORDERDETAILNO INTEGER generated always as identity(start with 1, increment by 1),
 ORDERNO INTEGER NOT NULL,
 ITEMNO INTEGER NOT NULL,
 ITEMCOUNT INTEGER,
 PRICE INTEGER,
 CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDERDETAILNO)
);

