DELETE FROM CUSTOMER;
INSERT INTO CUSTOMER (TELNO, "NAME", ADDRESS, ORDERCOUNT, SERVICECOUNT) VALUES ('0311111111', 'ヤマダタロウ', '新宿区AAA', 2, 0);
INSERT INTO CUSTOMER (TELNO, "NAME", ADDRESS, ORDERCOUNT, SERVICECOUNT) VALUES ('0322222222', 'スズキヨシノブ', '新宿区BBB', 5, 1);
INSERT INTO CUSTOMER (TELNO, "NAME", ADDRESS, ORDERCOUNT, SERVICECOUNT) VALUES ('0344444444', 'セキカワリョウ', '新宿区DDD', 1, 0);
INSERT INTO CUSTOMER (TELNO, "NAME", ADDRESS, ORDERCOUNT, SERVICECOUNT) VALUES ('0355555555', 'ファムラン', '新宿区EEE', 10, 2);


DELETE FROM ITEM;
alter table ITEM  alter column ITEMNO restart with 1;
alter table ORDERS alter column ORDERNO restart with 1;

DELETE FROM ORDERS;
DELETE FROM ORDERDETAIL;
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('ベトナム風ハムバンミー', 750);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('ビーフバンミー', 850);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('チキンバンミー', 750);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('照り焼きポークバンミー', 800);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('エビとアボカドバンミー', 800);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('生春巻き', 500);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('コーラMサイズ', 200);
INSERT INTO ITEM (ITEMNAME, PRICE) VALUES ('コーラLサイズ', 300);
